all:
  vars:
    ansible_user: root
    ansible_password: rootpass
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ubuntu_packages:
      - apache2
    redhat_packages:
      - mariadb-server
      - mariadb
    hello_world_content: "Hello world\n"
    web_server_document_root: "/var/www/html"
    web_server_index_file: "index.html"
  children:
    dev:
      hosts:
        ubuntu:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        redhat:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_python_interpreter: /usr/bin/python3.9